server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json #GZIP compression
    min-response-size: 1024
  undertow:
    threads:
      worker: 64 # generally should be high, at least 10 per CPU core. 1 thread ~= 2-3 MB
      io: 4 # one IO thread per CPU core is a reasonable default. #threads that will listen to new connections and put them into a queue https://undertow.io/undertow-docs/undertow-docs-2.1.0/listeners.html

spring:
  datasource:
    url: jdbc:mysql://${mysql.url}/${mysql.schema}?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${mysql.username}
    password: ${mysql.password}
    hikari:
      auto-commit: false
      connection-timeout: 250 # milliseconds. Best to keep it low, microservices should fail fast
      max-lifetime: 600000 # maximum amount of time the connection can live (10 min) - security.
      maximum-pool-size: 20 # max 20 DB simultaneous connections. More than that the DB will struggle. https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
      minimum-idle: 10 # during periods of low load, it can drop until 10 connections remain
      pool-name: master
  jpa:
    open-in-view: false # disable default connection opening/transaction at the controller (AKA view) level
    show-sql: true # print the queries
    hibernate:
      ddl-auto: none # or create/update/create-drop. Manages the HibernateDB schema
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.MySQL5InnoDBDialect
      "[hibernate.generate_statistics]": false # useful for troubleshooting
      "[hibernate.connection.provider_disables_autocommit]": true # during the creation of a transaction, without this config it would utilize one connection of the pool to verify if autocommit is enabled or disabled. With this config it will know that it is enabled/disabled
      # Para aumentar a performance ao m√°ximo, desabilitamos o auto-commit e o open-in-view.
      # https://vladmihalcea.com/why-you-should-always-use-hibernate-connection-provider_disables_autocommit-for-resource-local-jpa-transactions/