server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json #GZIP compression
    min-response-size: 1024
  undertow:
    threads:
      worker: 64 #generally should be high, at least 10 per CPU core. 1 thread ~= 2-3 MB
      io: 4 #one IO thread per CPU core is a reasonable default. #threads that will listen to new connections and put them into a queue https://undertow.io/undertow-docs/undertow-docs-2.1.0/listeners.html

spring:
  datasource:
    url: jdbc:mysql://${mysql.url}/${mysql.schema}?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${mysql.username}
    password: ${mysql.password}